In [1]:
import os
import torch
import numpy as np
import pandas as pd
from typing import Dict, List
import time
from dotenv import load_dotenv

from langchain_core.messages import ChatMessage
from langchain_core.prompts import ChatMessagePromptTemplate
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_text_splitters.base import TextSplitter

from financerag.common import get_query_and_retrieved_corpus_text, process_retrieval_df, get_final_result 
from financerag.task import *
from financerag.retrieval import DenseRetrieval
from financerag.hipporag import HippoRAG
from financerag.retrieval import BM25, BM25_Retriever
from financerag.rerank import CrossEncoderReranker

from sentence_transformers import CrossEncoder
from transformers import pipeline
import warnings
warnings.filterwarnings('ignore')

/Users/mac/Desktop/Code/Personal_Project/DeepLearningProject/RAG_Project/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
load_dotenv(".env")
GG_API_KEY = os.environ.get('GOOGLE_API_KEY')
PINECONE_API_KEY = os.environ.get('PINECONE_API_KEY')

In [3]:
def load_query(dataset_name : str, new_path_to_query = None) -> Dict[str, str]:
    query_df = pd.read_json(f"finance_dataset/{dataset_name.lower()}_queries.jsonl/queries.jsonl", lines = True)
    # Convert into Dict[str, str]
    query_dict = {row['_id'] : row['text'] for i, row in query_df.iterrows()}
    return query_dict

    
def load_corpus(dataset_name : str, new_path_to_corpus = None) -> Dict[str, str]:
    corpus_df = pd.read_json(f"finance_dataset/{dataset_name.lower()}_corpus.jsonl/corpus.jsonl", lines = True)
    # Convert into Dict[str, str]
    corpus_dict = {row['_id'] : row['text'] for i, row in corpus_df.iterrows()}
    return corpus_dict

In [4]:
# Set up vector database
import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS
embeddings = GoogleGenerativeAIEmbeddings(model = "models/text-embedding-004", request_options = {'timeout' : 100000})
index = faiss.IndexFlatL2(len(embeddings.embed_query("hello world")))

vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

In [5]:
def get_vector_store():
    embeddings = GoogleGenerativeAIEmbeddings(model = "models/text-embedding-004",  request_options = {'timeout' : 100000})
    index = faiss.IndexFlatL2(len(embeddings.embed_query("hello world")))
    
    vector_store = FAISS(
        embedding_function=embeddings,
        index=index,
        docstore=InMemoryDocstore(),
        index_to_docstore_id={},
    )
    return vector_store

In [6]:
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")

device = 'mps' if torch.backends.mps.is_available() else 'cpu'
device

'mps'

In [7]:
# Get dataset name first
import os
dataset_names = []
for f in os.listdir('finance_dataset'):
    if f.endswith("tsv"):
       dataset_names.append(f.split('_')[0])
dataset_names

['MultiHeirtt',
 'FinQA',
 'FinanceBench',
 'ConvFinQA',
 'FinQABench',
 'TATQA',
 'FinDER']

In [8]:
CHUNK_SIZE = 1200
CHUNK_OVERLAP = 300
text_splitter = RecursiveCharacterTextSplitter(chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP)

In [12]:
for dataset_name in dataset_names:
    task_variable = f"{dataset_name.lower()}_task"
    script_string = f"""
    # {dataset_name} Task
    print(f"{dataset_name} task")
    {task_variable} = {dataset_name}Task()
    {task_variable}.load()
    {task_variable}_max_len = np.max([len(text) for text in {task_variable}.corpus.values()])
    {task_variable}_top_k = ({task_variable}_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    print("Retrieve", {task_variable}_top_k, f"documents/query for {dataset_name} task")
    vector_store = get_vector_store()
    {task_variable}_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = {task_variable}.metadata.dataset_name)
    {task_variable}_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = {task_variable}.corpus, saved_index = False, batch_size = 500)

    {task_variable}_result = {task_variable}.retrieve(retriever = {task_variable}_retriever, top_k = {task_variable}_top_k)
    {task_variable}_reranker = CrossEncoderReranker(queries = {task_variable}.queries, corpus = {task_variable}.corpus, reranker = model)
    {task_variable}_final_result = {task_variable}_reranker.rerank(retrieved_result = {task_variable}_result, top_k = 10)
    {task_variable}.save_retrieved_results({task_variable}_final_result, method_name = 'dense_retrieval_split_document_and_reranking')
    """
    print(script_string)

    # MultiHeirtt Task
    print(f"MultiHeirtt task")
    multiheirtt_task = MultiHeirttTask()
    multiheirtt_task.load()
    multiheirtt_task_max_len = np.max([len(text) for text in multiheirtt_task.corpus.values()])
    multiheirtt_task_top_k = (multiheirtt_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    print("Retrieve", multiheirtt_task_top_k, f"documents/query for MultiHeirtt task")
    vector_store = get_vector_store()
    multiheirtt_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = multiheirtt_task.metadata.dataset_name)
    multiheirtt_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = multiheirtt_task.corpus, saved_index = False, batch_size = 500)

    multiheirtt_task_result = multiheirtt_task.retrieve(retriever = multiheirtt_task_retriever, top_k = multiheirtt_task_top_k)
    multiheirtt_task_reranker = CrossEncoderReranker(queries = multiheirtt_task.queries, corpus = multiheirtt_task.corpus, reranker = model)
    multiheirtt_task_final_result = multiheirtt_task_reranker.rerank(retrieved_result = multiheirtt_task_result, top_k = 10)
    multiheirtt_task.save_retrieved_results(multiheirtt_task_final_result, method_name = 'dense_retrieval_split_document_and_reranking')


    # FinQA Task
    print(f"FinQA task")
    finqa_task = FinQATask()
    finqa_task.load()
    finqa_task_max_len = np.max([len(text) for text in finqa_task.corpus.values()])
    finqa_task_top_k = (finqa_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    print("Retrieve", finqa_task_top_k, f"documents/query for FinQA task")
    vector_store = get_vector_store()
    finqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqa_task.metadata.dataset_name)
    finqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finqa_task.corpus, saved_index = False, batch_size = 500)

    finqa_task_result = finqa_task.retrieve(retriever = finqa_task_retriever, top_k = finqa_task_top_k)
    finqa_task_reranker = CrossEncoderReranker(queries = finqa_task.queries, corpus = finqa_task.corpus, reranker = model)
    finqa_task_final_result = finqa_task_reranker.rerank(retrieved_result = finqa_task_result, top_k = 10)
    finqa_task.save_retrieved_results(finqa_task_final_result, method_name = 'dense_retrieval_split_document_and_reranking')


    # FinanceBench Task
    print(f"FinanceBench task")
    financebench_task = FinanceBenchTask()
    financebench_task.load()
    financebench_task_max_len = np.max([len(text) for text in financebench_task.corpus.values()])
    financebench_task_top_k = (financebench_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    print("Retrieve", financebench_task_top_k, f"documents/query for FinanceBench task")
    vector_store = get_vector_store()
    financebench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = financebench_task.metadata.dataset_name)
    financebench_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = financebench_task.corpus, saved_index = False, batch_size = 500)

    financebench_task_result = financebench_task.retrieve(retriever = financebench_task_retriever, top_k = financebench_task_top_k)
    financebench_task_reranker = CrossEncoderReranker(queries = financebench_task.queries, corpus = financebench_task.corpus, reranker = model)
    financebench_task_final_result = financebench_task_reranker.rerank(retrieved_result = financebench_task_result, top_k = 10)
    financebench_task.save_retrieved_results(financebench_task_final_result, method_name = 'dense_retrieval_split_document_and_reranking')


    # ConvFinQA Task
    print(f"ConvFinQA task")
    convfinqa_task = ConvFinQATask()
    convfinqa_task.load()
    convfinqa_task_max_len = np.max([len(text) for text in convfinqa_task.corpus.values()])
    convfinqa_task_top_k = (convfinqa_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    print("Retrieve", convfinqa_task_top_k, f"documents/query for ConvFinQA task")
    vector_store = get_vector_store()
    convfinqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = convfinqa_task.metadata.dataset_name)
    convfinqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = convfinqa_task.corpus, saved_index = False, batch_size = 500)

    convfinqa_task_result = convfinqa_task.retrieve(retriever = convfinqa_task_retriever, top_k = convfinqa_task_top_k)
    convfinqa_task_reranker = CrossEncoderReranker(queries = convfinqa_task.queries, corpus = convfinqa_task.corpus, reranker = model)
    convfinqa_task_final_result = convfinqa_task_reranker.rerank(retrieved_result = convfinqa_task_result, top_k = 10)
    convfinqa_task.save_retrieved_results(convfinqa_task_final_result, method_name = 'dense_retrieval_split_document_and_reranking')


    # FinQABench Task
    print(f"FinQABench task")
    finqabench_task = FinQABenchTask()
    finqabench_task.load()
    finqabench_task_max_len = np.max([len(text) for text in finqabench_task.corpus.values()])
    finqabench_task_top_k = (finqabench_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    print("Retrieve", finqabench_task_top_k, f"documents/query for FinQABench task")
    vector_store = get_vector_store()
    finqabench_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqabench_task.metadata.dataset_name)
    finqabench_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finqabench_task.corpus, saved_index = False, batch_size = 500)

    finqabench_task_result = finqabench_task.retrieve(retriever = finqabench_task_retriever, top_k = finqabench_task_top_k)
    finqabench_task_reranker = CrossEncoderReranker(queries = finqabench_task.queries, corpus = finqabench_task.corpus, reranker = model)
    finqabench_task_final_result = finqabench_task_reranker.rerank(retrieved_result = finqabench_task_result, top_k = 10)
    finqabench_task.save_retrieved_results(finqabench_task_final_result, method_name = 'dense_retrieval_split_document_and_reranking')


    # TATQA Task
    print(f"TATQA task")
    tatqa_task = TATQATask()
    tatqa_task.load()
    tatqa_task_max_len = np.max([len(text) for text in tatqa_task.corpus.values()])
    tatqa_task_top_k = (tatqa_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    print("Retrieve", tatqa_task_top_k, f"documents/query for TATQA task")
    vector_store = get_vector_store()
    tatqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = tatqa_task.metadata.dataset_name)
    tatqa_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = tatqa_task.corpus, saved_index = False, batch_size = 500)

    tatqa_task_result = tatqa_task.retrieve(retriever = tatqa_task_retriever, top_k = tatqa_task_top_k)
    tatqa_task_reranker = CrossEncoderReranker(queries = tatqa_task.queries, corpus = tatqa_task.corpus, reranker = model)
    tatqa_task_final_result = tatqa_task_reranker.rerank(retrieved_result = tatqa_task_result, top_k = 10)
    tatqa_task.save_retrieved_results(tatqa_task_final_result, method_name = 'dense_retrieval_split_document_and_reranking')


    # FinDER Task
    print(f"FinDER task")
    finder_task = FinDERTask()
    finder_task.load()
    finder_task_max_len = np.max([len(text) for text in finder_task.corpus.values()])
    finder_task_top_k = (finder_task_max_len // (CHUNK_SIZE - CHUNK_OVERLAP) + 1) * 10 + 10
    print("Retrieve", finder_task_top_k, f"documents/query for FinDER task")
    vector_store = get_vector_store()
    finder_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finder_task.metadata.dataset_name)
    finder_task_retriever.load_corpus_with_splitting(text_splitter = text_splitter, corpus = finder_task.corpus, saved_index = False, batch_size = 500)

    finder_task_result = finder_task.retrieve(retriever = finder_task_retriever, top_k = finder_task_top_k)
    finder_task_reranker = CrossEncoderReranker(queries = finder_task.queries, corpus = finder_task.corpus, reranker = model)
    finder_task_final_result = finder_task_reranker.rerank(retrieved_result = finder_task_result, top_k = 10)
    finder_task.save_retrieved_results(finder_task_final_result, method_name = 'dense_retrieval_split_document_and_reranking')

In [14]:
model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L6-v2", device=device)

In [11]:
print(f"FinanceBench task")
financebench_task = FinanceBenchTask()
financebench_task.load()
hippo_rag = HippoRAG(retriever=vector_store)

FinanceBench task

Some weights of the model checkpoint at dslim/bert-base-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use mps:0

In [14]:
corpus = {}
for i, (corpus_id, corpus_text) in enumerate(financebench_task.corpus.items()):
    corpus[corpus_id] = corpus_text
    if i == 10: break
corpus

{'dd2af2336': 'PEPSICO_2022_10K 6) Africa, Middle East and South Asia (AMESA), which includes all of our beverage and convenient food businesses in\nAfrica, the Middle East and South Asia; and\n7) Asia Pacific, Australia and New Zealand and China Region (APAC), which includes all of our beverage and convenient\nfood businesses in Asia Pacific, Australia and New Zealand, and China region.',
 'dd2acf5c0': 'BOEING_2022_10K We derive a significant portion of our revenues from a limited number of commercial airlines.',
 'dd2ad12e4': 'COCACOLA_2022_10K THE COCA-COLA COMPANY AND SUBSIDIARIES\nCONSOLIDATED STATEMENTS OF CASH FLOWS\n(In millions)\nYear Ended December 31,\n2022\n2021\n2020\nOperating Activities\n \n \nConsolidated net income\n$\n9,571 $\n9,804 $\n7,768 \nDepreciation and amortization\n1,260 \n1,452 \n1,536 \nStock-based compensation expense\n356 \n337 \n126 \nDeferred income taxes\n(122)\n894 \n(18)\nEquity (income) loss net of dividends\n(838)\n(615)\n(511)\nForeign currency adjustments\n203 \n86 \n(88)\nSignificant (gains) losses net\n(129)\n(1,365)\n(914)\nOther operating charges\n1,086 \n506 \n556 \nOther items\n236 \n201 \n699 \nNet change in operating assets and liabilities\n(605)\n1,325 \n690 \nNet Cash Provided by Operating Activities\n11,018 \n12,625 \n9,844 \nInvesting Activities\n \n \nPurchases of investments\n(3,751)\n(6,030)\n(13,583)\nProceeds from disposals of investments\n4,771 \n7,059 \n13,835 \nAcquisitions of businesses, equity method investments and nonmarketable securities\n(73)\n(4,766)\n(1,052)\nProceeds from disposals of businesses, equity method investments and nonmarketable securities\n458 \n2,180 \n189 \nPurchases of property, plant and equipment\n(1,484)\n(1,367)\n(1,177)\nProceeds from disposals of property, plant and equipment\n75 \n108 \n189 \nCollateral (paid) received associated with hedging activities net\n(1,465)\n \n \nOther investing activities\n706 \n51 \n122 \nNet Cash Provided by (Used in) Investing Activities\n(763)\n(2,765)\n(1,477)\nFinancing Activities\n \n \nIssuances of debt\n3,972 \n13,094 \n26,934 \nPayments of debt\n(4,930)\n(12,866)\n(28,796)\nIssuances of stock\n837 \n702 \n647 \nPurchases of stock for treasury\n(1,418)\n(111)\n(118)\nDividends\n(7,616)\n(7,252)\n(7,047)\nOther financing activities\n(1,095)\n(353)\n310 \nNet Cash Provided by (Used in) Financing Activities\n(10,250)\n(6,786)\n(8,070)\nEffect of Exchange Rate Changes on Cash, Cash Equivalents, Restricted Cash and\n Restricted Cash Equivalents\n(205)\n(159)\n76 \nCash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents\n \n \nNet increase (decrease) in cash, cash equivalents, restricted cash and restricted cash\n equivalents during the year\n(200)\n2,915 \n373 \nCash, cash equivalents, restricted cash and restricted cash equivalents at beginning of year\n10,025 \n7,110 \n6,737 \nCash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents at End of Year\n9,825 \n10,025 \n7,110 \nLess: Restricted cash and restricted cash equivalents at end of year\n306 \n341 \n315 \nCash and Cash Equivalents at End of Year\n$\n9,519 $\n9,684 $\n6,795 \nRefer to Notes to Consolidated Financial Statements.\n64',
 'dd2af3272': 'PEPSICO_2022_10K Note 3 Restructuring and Impairment Charges\n2019 Multi-Year Productivity Plan\nWe publicly announced a multi-year productivity plan on February 15, 2019 (2019 Productivity Plan) that will leverage new\ntechnology and business models to further simplify, harmonize and automate processes; re-engineer our go-to-market and\ninformation systems, including deploying the right automation for each market; and simplify our organization and optimize our\nmanufacturing and supply chain footprint. To build on the successful implementation of the 2019 Productivity Plan, in the fourth\nquarter of 2022, we expanded and extended the plan through the end of 2028 to take advantage of additional opportunities within\nthe initiatives described above. As a result, we expect to incur pre-tax charges of approximately $3.65 billion, including cash\nexpenditures of approximately $2.9 billion. These pre-tax charges are expected to consist of approximately 55% of severance and\nother employee-related costs, 10% for asset impairments (all non-cash) resulting from plant closures and related actions and 35%\nfor other costs associated with the implementation of our initiatives.\nThe total plan pre-tax charges are expected to be incurred by division approximately as follows:\nFLNA\nQFNA\nPBNA\nLatAm\nEurope\nAMESA\nAPAC\nCorporate\nExpected pre-tax charges\n15 %\n1 %\n25 %\n10 %\n25 %\n5 %\n4 %\n15 %\nA summary of our 2019 Productivity Plan charges is as follows:\n2022\n2021\n2020\nCost of sales\n$\n33 \n$\n29 $\n30 \nSelling, general and administrative expenses\n347 \n208 \n239 \nOther pension and retiree medical benefits expense\n31 \n10 \n20 \nTotal restructuring and impairment charges\n$\n411 \n$\n247 $\n289',
 'dd2ade412': 'LOCKHEEDMARTIN_2020_10K Table of Contents\nLockheed Martin Corporation\nConsolidated Balance Sheets\n(in millions, except par value)\n \n \nDecember 31,\n2020\n2019\nAssets\nCurrent assets\nCash and cash equivalents\n$\n3,160 \n$\n1,514 \nReceivables, net\n1,978 \n2,337 \nContract assets\n9,545 \n9,094 \nInventories\n3,545 \n3,619 \nOther current assets\n1,150 \n531 \nTotal current assets\n19,378 \n17,095 \nProperty, plant and equipment, net\n7,213 \n6,591 \nGoodwill\n10,806 \n10,604 \nIntangible assets, net\n3,012 \n3,213 \nDeferred income taxes\n3,475 \n3,319 \nOther noncurrent assets\n6,826 \n6,706 \nTotal assets\n$\n50,710 \n$\n47,528 \nLiabilities and equity\nCurrent liabilities\nAccounts payable\n$\n880 \n$\n1,281 \nContract liabilities\n7,545 \n7,054 \nSalaries, benefits and payroll taxes\n3,163 \n2,466 \nCurrent maturities of long-term debt\n500 \n1,250 \nOther current liabilities\n1,845 \n1,921 \nTotal current liabilities\n13,933 \n13,972 \nLong-term debt, net\n11,669 \n11,404 \nAccrued pension liabilities\n12,874 \n13,234 \nOther noncurrent liabilities\n6,196 \n5,747 \nTotal liabilities\n44,672 \n44,357 \nStockholders equity\nCommon stock, $1 par value per share\n279 \n280 \nAdditional paid-in capital\n221 \n \nRetained earnings\n21,636 \n18,401 \nAccumulated other comprehensive loss\n(16,121)\n(15,554)\nTotal stockholders equity\n6,015 \n3,127 \nNoncontrolling interests in subsidiary\n23 \n44 \nTotal equity\n6,038 \n3,171 \nTotal liabilities and equity\n$\n50,710 \n$\n47,528 \nThe accompanying notes are an integral part of these consolidated financial statements.\n69',
 'dd2b02da8': 'ULTABEAUTY_2023_10K Ulta Beauty, Inc.\nConsolidated Statements of Cash Flows\nFiscal year ended\nJanuary 28,\nJanuary 29,\nJanuary 30,\n(In thousands)\n2023\n \n2022\n \n2021\nOperating activities\nNet income\n$\n1,242,408\n$\n985,837\n$\n175,835\nAdjustments to reconcile net income to net cash provided by operating activities:\nDepreciation and amortization\n241,372\n268,460\n297,772\nNon-cash lease expense\n301,912\n276,229\n268,071\nLong-lived asset impairment charge\n\n\n72,533\nDeferred income taxes\n15,653\n(25,666)\n(24,008)\nStock-based compensation expense\n43,044\n47,259\n27,583\nLoss on disposal of property and equipment\n6,688\n5,358\n6,827\nChange in operating assets and liabilities:\nReceivables\n34,260\n(40,573)\n(53,772)\nMerchandise inventories\n(104,233)\n(331,003)\n125,486\nPrepaid expenses and other current assets\n(19,432)\n(3,412)\n(4,363)\nIncome taxes\n(45,182)\n(35,652)\n58,916\nAccounts payable\n8,309\n66,156\n62,324\nAccrued liabilities\n48,249\n58,598\n58,599\nDeferred revenue\n41,098\n79,196\n36,848\nOperating lease liabilities\n(324,500)\n(303,914)\n(297,513)\nOther assets and liabilities\n(7,731)\n12,392\n(783)\nNet cash provided by operating activities\n1,481,915\n1,059,265\n810,355\nInvesting activities\nProceeds from short-term investments\n\n\n110,000\nCapital expenditures\n(312,126)\n(172,187)\n(151,866)\nAcquisitions, net of cash acquired\n\n\n(1,220)',
 'dd2aeab5e': 'NETFLIX_2015_10K Table of Contents\nNETFLIX, INC.\nCONSOLIDATED STATEMENTS OF CASH FLOWS\n(in thousands)\n \n \nYear Ended December 31,\n \n \n2015\n \n2014\n \n2013\nCash flows from operating activities:\n \n \n \nNet income\n $\n122,641 $\n266,799 $\n112,403\nAdjustments to reconcile net income to net cash (used in) provided by operating activities:\n \n \n \nAdditions to streaming content assets\n \n(5,771,652) \n(3,773,019) \n(3,030,701)\nChange in streaming content liabilities\n \n1,162,413 \n593,125 \n673,785\nAmortization of streaming content assets\n \n3,405,382 \n2,656,279 \n2,121,981\nAmortization of DVD content assets\n \n79,380 \n71,491 \n71,325\nDepreciation and amortization of property, equipment and intangibles\n \n62,283 \n54,028 \n48,374\nStock-based compensation expense\n \n124,725 \n115,239 \n73,100\nExcess tax benefits from stock-based compensation\n \n(80,471) \n(89,341) \n(81,663)\nOther non-cash items\n \n31,628 \n15,282 \n5,332\nLoss on extinguishment of debt\n \n \n \n25,129\nDeferred taxes\n \n(58,655) \n(30,063) \n(22,044)\nChanges in operating assets and liabilities:\n \n \n \nOther current assets\n \n18,693 \n(9,198) \n43,177\nAccounts payable\n \n51,615 \n83,812 \n18,374\nAccrued expenses\n \n48,810 \n55,636 \n1,941\nDeferred revenue\n \n72,135 \n58,819 \n46,295\nOther non-current assets and liabilities\n \n(18,366) \n(52,406) \n(8,977)\nNet cash (used in) provided by operating activities\n \n(749,439) \n16,483 \n97,831\nCash flows from investing activities:\n \n \n \nAcquisition of DVD content assets\n \n(77,958) \n(74,790) \n(65,927)\nPurchases of property and equipment\n \n(91,248) \n(69,726) \n(54,143)\nOther assets\n \n(1,912) \n1,334 \n5,939\nPurchases of short-term investments\n \n(371,915) \n(426,934) \n(550,264)\nProceeds from sale of short-term investments\n \n259,079 \n385,300 \n347,502\nProceeds from maturities of short-term investments\n \n104,762 \n141,950 \n60,925\nNet cash used in investing activities\n \n(179,192) \n(42,866) \n(255,968)\nCash flows from financing activities:\n \n \n \nProceeds from issuance of common stock\n \n77,980 \n60,544 \n124,557\nProceeds from issuance of debt\n \n1,500,000 \n400,000 \n500,000\nIssuance costs\n \n(17,629) \n(7,080) \n(9,414)\nRedemption of debt\n \n \n \n(219,362)\nExcess tax benefits from stock-based compensation\n \n80,471 \n89,341 \n81,663\nPrincipal payments of lease financing obligations\n \n(545) \n(1,093) \n(1,180)\nNet cash provided by financing activities\n \n1,640,277 \n541,712 \n476,264\nEffect of exchange rate changes on cash and cash equivalents\n \n(15,924) \n(6,686) \n(3,453)\nNet increase in cash and cash equivalents\n \n695,722 \n508,643 \n314,674\nCash and cash equivalents, beginning of year\n \n1,113,608 \n604,965 \n290,291\nCash and cash equivalents, end of year\n $\n1,809,330 $\n1,113,608 $\n604,965\nSupplemental disclosure:\n \n \n \nIncome taxes paid\n $\n27,658 $\n50,573 $\n7,465\nInterest paid\n \n111,761 \n41,085 \n19,114\nInvesting activities included in liabilities\n \n18,824 \n23,802 \n11,508\nSee accompanying notes to consolidated financial statements.\n40',
 'dd2af9b04': 'PFIZER_2021_10K As of December 31,\n(MILLIONS, EXCEPT PER COMMON SHARE DATA)\n2021\n2020\nAssets\nCash and cash equivalents\n$\n1,944 \n$\n1,786 \nShort-term investments\n29,125 \n10,437 \nTrade accounts receivable, less allowance for doubtful accounts: 2021$492; 2020$508\n11,479 \n7,913 \nInventories\n9,059 \n8,020 \nCurrent tax assets\n4,266 \n3,264 \nOther current assets\n3,820 \n3,646 \nTotal current assets\n59,693 \n35,067 \nEquity-method investments\n16,472 \n16,856 \nLong-term investments\n5,054 \n3,406 \nProperty, plant and equipment\n14,882 \n13,745',
 'dd2ade854': 'LOCKHEEDMARTIN_2021_10K Table of Contents\nLockheed Martin Corporation\nConsolidated Balance Sheets\n(in millions, except par value)\n \n \nDecember 31,\n2021\n2020\nAssets\nCurrent assets\nCash and cash equivalents\n$\n3,604 \n$\n3,160 \nReceivables, net\n1,963 \n1,978 \nContract assets\n10,579 \n9,545 \nInventories\n2,981 \n3,545 \nOther current assets\n688 \n1,150 \nTotal current assets\n19,815 \n19,378 \nProperty, plant and equipment, net\n7,597 \n7,213 \nGoodwill\n10,813 \n10,806 \nIntangible assets, net\n2,706 \n3,012 \nDeferred income taxes\n2,290 \n3,475 \nOther noncurrent assets\n7,652 \n6,826 \nTotal assets\n$\n50,873 \n$\n50,710 \nLiabilities and equity\nCurrent liabilities\nAccounts payable\n$\n780 \n$\n880 \nSalaries, benefits and payroll taxes\n3,108 \n3,163 \nContract liabilities\n8,107 \n7,545 \nCurrent maturities of long-term debt\n6 \n500 \nOther current liabilities\n1,996 \n1,845 \nTotal current liabilities\n13,997 \n13,933 \nLong-term debt, net\n11,670 \n11,669 \nAccrued pension liabilities\n8,319 \n12,874 \nOther noncurrent liabilities\n5,928 \n6,196 \nTotal liabilities\n39,914 \n44,672 \nStockholders equity\nCommon stock, $1 par value per share\n271 \n279 \nAdditional paid-in capital\n94 \n221 \nRetained earnings\n21,600 \n21,636 \nAccumulated other comprehensive loss\n(11,006)\n(16,121)\nTotal stockholders equity\n10,959 \n6,015 \nNoncontrolling interests in subsidiary\n \n23 \nTotal equity\n10,959 \n6,038 \nTotal liabilities and equity\n$\n50,873 \n$\n50,710 \nThe accompanying notes are an integral part of these consolidated financial statements.\n68',
 'dd2ad7824': "GENERALMILLS_2020_10K 50 \n \nConsolidated Balance Sheets \nGENERAL MILLS, INC. AND SUBSIDIARIES \n(In Millions, Except Par Value) \n \nMay 31, 2020 \nMay 26, 2019 \nASSETS \n \n \n \n \nCurrent assets: \n \n \n \n \nCash and cash equivalents \n$ \n1,677.8 $ \n450.0 \nReceivables \n \n1,615.1 \n1,679.7 \nInventories \n \n1,426.3 \n1,559.3 \nPrepaid expenses and other current assets \n \n402.1 \n497.5 \nTotal current assets \n \n5,121.3 \n4,186.5 \nLand, buildings, and equipment \n \n3,580.6 \n3,787.2 \nGoodwill \n \n13,923.2 \n13,995.8 \nOther intangible assets \n \n7,095.8 \n7,166.8 \nOther assets \n \n1,085.8 \n974.9 \nTotal assets \n$ \n30,806.7 $ \n30,111.2 \n \n \n \n \n \nLIABILITIES AND EQUITY \n \n \n \n \nCurrent liabilities: \n \n \n \n \nAccounts payable \n$ \n3,247.7 $ \n2,854.1 \nCurrent portion of long-term debt \n \n2,331.5 \n1,396.5 \nNotes payable \n \n279.0 \n1,468.7 \nOther current liabilities \n \n1,633.3 \n1,367.8 \nTotal current liabilities \n \n7,491.5 \n7,087.1 \nLong-term debt \n \n10,929.0 \n11,624.8 \nDeferred income taxes \n \n1,947.1 \n2,031.0 \nOther liabilities \n \n1,545.0 \n1,448.9 \nTotal liabilities \n \n21,912.6 \n22,191.8 \nRedeemable interest \n \n544.6 \n551.7 \nStockholders' equity: \n \n \n \n \nCommon stock, 754.6 shares issued, $0.10 par value \n \n75.5 \n75.5 \nAdditional paid-in capital \n \n1,348.6 \n1,386.7 \nRetained earnings \n \n15,982.1 \n14,996.7 \nCommon stock in treasury, at cost, shares of 144.8 and 152.7 \n \n(6,433.3) \n(6,779.0)\nAccumulated other comprehensive loss \n \n(2,914.4) \n(2,625.4)\nTotal stockholders' equity \n \n8,058.5 \n7,054.5 \nNoncontrolling interests \n \n291.0 \n313.2 \nTotal equity \n \n8,349.5 \n7,367.7 \nTotal liabilities and equity \n$ \n30,806.7 $ \n30,111.2 \nSee accompanying notes to consolidated financial statements.",
 'dd2ac04a8': 'AMAZON_2019_10K Table of Contents\nAMAZON.COM, INC.\nCONSOLIDATED STATEMENTS OF OPERATIONS\n(in millions, except per share data)\n \n \nYear Ended December 31,\n \n2017\n \n2018\n \n2019\nNet product sales\n$\n118,573 $\n141,915 $\n160,408\nNet service sales\n59,293 \n90,972 \n120,114\nTotal net sales\n177,866 \n232,887 \n280,522\nOperating expenses:\n \n \n \nCost of sales\n111,934 \n139,156 \n165,536\nFulfillment\n25,249 \n34,027 \n40,232\nTechnology and content\n22,620 \n28,837 \n35,931\nMarketing\n10,069 \n13,814 \n18,878\nGeneral and administrative\n3,674 \n4,336 \n5,203\nOther operating expense (income), net\n214 \n296 \n201\nTotal operating expenses\n173,760 \n220,466 \n265,981\nOperating income\n4,106 \n12,421 \n14,541\nInterest income\n202 \n440 \n832\nInterest expense\n(848) \n(1,417) \n(1,600)\nOther income (expense), net\n346 \n(183) \n203\nTotal non-operating income (expense)\n(300) \n(1,160) \n(565)\nIncome before income taxes\n3,806 \n11,261 \n13,976\nProvision for income taxes\n(769) \n(1,197) \n(2,374)\nEquity-method investment activity, net of tax\n(4) \n9 \n(14)\nNet income\n$\n3,033 $\n10,073 $\n11,588\nBasic earnings per share\n$\n6.32 $\n20.68 $\n23.46\nDiluted earnings per share\n$\n6.15 $\n20.14 $\n23.01\nWeighted-average shares used in computation of earnings per share:\n \n \n \nBasic\n480 \n487 \n494\nDiluted\n493 \n500 \n504\nSee accompanying notes to consolidated financial statements.\n38'}

In [34]:
hippo_rag.offline_indexing(corpus = corpus, batch_size = 16)
hippo_rag.retrieve(queries = financebench_task.queries, corpus = corpus, top_k = 10)

Loading: 100%|██████████| 1/1 [00:04<00:00,  4.14s/it]
Add nodes to KG: 100%|██████████| 11/11 [00:00<00:00, 66672.46it/s]
Construct matrix P: 100%|██████████| 11/11 [00:00<00:00, 104857.60it/s]
Retrieving: 100%|██████████| 150/150 [01:34<00:00,  1.58it/s]

{'qd2ac917a': {'dd2af3272': 40.368421052631575,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2aeff00': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2acfe6c': {'dd2ade412': 23.013513513513512,
  'dd2ade854': 14.054054054054053,
  'dd2ad7824': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ad28d8': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac61e6': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2acf836': {'dd2ade412': 23.013513513513512,
  'dd2ade854': 14.054054054054053,
  'dd2ad7824': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2abf012': {'dd2ade412': 23.013513513513512,
  'dd2ade854': 14.054054054054053,
  'dd2ad7824': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2abbd7c': {'dd2af2336': 1.0,
  'dd2acf5c0': 1.0,
  'dd2ad12e4': 1.0,
  'dd2af3272': 1.0,
  'dd2ade412': 1.0,
  'dd2b02da8': 1.0,
  'dd2aeab5e': 1.0,
  'dd2af9b04': 1.0,
  'dd2ade854': 1.0,
  'dd2ad7824': 1.0},
 'qd2adb780': {'dd2b02da8': 4.56140350877193,
  'dd2af3272': 4.56140350877193,
  'dd2ade412': 3.87719298245614,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ade0e8': {'dd2ade412': 11.058441558441558,
  'dd2ade854': 6.753246753246753,
  'dd2af3272': 6.753246753246753,
  'dd2ad7824': 2.8701298701298703,
  'dd2ac04a8': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2adc6da': {'dd2af2336': 26.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2ae6158': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ae56fe': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2addac6': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2af58c4': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac8e0a': {'dd2af3272': 40.368421052631575,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2b05f08': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2adca40': {'dd2af2336': 26.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2af2e3a': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2af4a50': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2b12b72': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2abe6b2': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2adba1e': {'dd2b02da8': 6.746506986027945,
  'dd2ade412': 5.734530938123752,
  'dd2af3272': 0.5189620758483035,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2adc342': {'dd2af2336': 26.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2ac019c': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac297e': {'dd2af2336': 1.0,
  'dd2acf5c0': 1.0,
  'dd2ad12e4': 1.0,
  'dd2af3272': 1.0,
  'dd2ade412': 1.0,
  'dd2b02da8': 1.0,
  'dd2aeab5e': 1.0,
  'dd2af9b04': 1.0,
  'dd2ade854': 1.0,
  'dd2ad7824': 1.0},
 'qd2b0876c': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2abb228': {'dd2af2336': 1.0,
  'dd2acf5c0': 1.0,
  'dd2ad12e4': 1.0,
  'dd2af3272': 1.0,
  'dd2ade412': 1.0,
  'dd2b02da8': 1.0,
  'dd2aeab5e': 1.0,
  'dd2af9b04': 1.0,
  'dd2ade854': 1.0,
  'dd2ad7824': 1.0},
 'qd2ad86c0': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2acde96': {'dd2ade412': 23.013513513513512,
  'dd2ade854': 14.054054054054053,
  'dd2ad7824': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ad110e': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2abc7c2': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2acf4d0': {'dd2ade412': 23.013513513513512,
  'dd2ade854': 14.054054054054053,
  'dd2ad7824': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2b0536e': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2abed24': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2abb7e6': {'dd2af2336': 1.0,
  'dd2acf5c0': 1.0,
  'dd2ad12e4': 1.0,
  'dd2af3272': 1.0,
  'dd2ade412': 1.0,
  'dd2b02da8': 1.0,
  'dd2aeab5e': 1.0,
  'dd2af9b04': 1.0,
  'dd2ade854': 1.0,
  'dd2ad7824': 1.0},
 'qd2ae689c': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ad7216': {'dd2b02da8': 6.525096525096525,
  'dd2ade412': 5.546332046332045,
  'dd2af2336': 1.3552123552123554,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2ada61e': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ad76bc': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac15c4': {'dd2af2336': 18.97297297297297,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2ac3676': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2add4d6': {'dd2af2336': 26.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2ad44a8': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ae159a': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ad682a': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac4dbe': {'dd2af2336': 12.315789473684209,
  'dd2af3272': 4.56140350877193,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0},
 'qd2ac4530': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ae758a': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2aecf94': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac5b24': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac13da': {'dd2af2336': 18.97297297297297,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2ac0d22': {'dd2af2336': 18.97297297297297,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2af258e': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2b0310e': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2afe1ae': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2b1698e': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ad18ca': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac0732': {'dd2af2336': 18.97297297297297,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2afa130': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2aeaf50': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ace92c': {'dd2ade412': 23.013513513513512,
  'dd2ade854': 14.054054054054053,
  'dd2ad7824': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac48d2': {'dd2af2336': 18.97297297297297,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2ad2568': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2afbdf0': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2b02664': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac3cc0': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2abe9be': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2af7502': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac27b2': {'dd2af2336': 1.0,
  'dd2acf5c0': 1.0,
  'dd2ad12e4': 1.0,
  'dd2af3272': 1.0,
  'dd2ade412': 1.0,
  'dd2b02da8': 1.0,
  'dd2aeab5e': 1.0,
  'dd2af9b04': 1.0,
  'dd2ade854': 1.0,
  'dd2ad7824': 1.0},
 'qd2abc4b6': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2af095a': {'dd2b02da8': 4.56140350877193,
  'dd2af3272': 4.56140350877193,
  'dd2ade412': 3.87719298245614,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2acda90': {'dd2ade412': 23.013513513513512,
  'dd2ade854': 14.054054054054053,
  'dd2ad7824': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2af1134': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2abfa1c': {'dd2af2336': 18.97297297297297,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2abd6b8': {'dd2b02da8': 7.027027027027026,
  'dd2ade412': 5.972972972972972,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2abd0e6': {'dd2b02da8': 5.531914893617022,
  'dd2af2336': 5.531914893617022,
  'dd2ade412': 4.702127659574469,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2adf038': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ad1d98': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2add044': {'dd2af2336': 26.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2af3272': 0.0,
  'dd2ad12e4': 0.0},
 'qd2aede94': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2af51e4': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac2cee': {'dd2af3272': 13.0,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ac1970': {'dd2af2336': 12.315789473684209,
  'dd2af3272': 4.56140350877193,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2b02da8': 0.0,
  'dd2ade412': 0.0,
  'dd2ad12e4': 0.0},
 'qd2b14ff8': {'dd2b02da8': 4.56140350877193,
  'dd2af3272': 4.56140350877193,
  'dd2ade412': 3.87719298245614,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2ad12e4': 0.0,
  'dd2acf5c0': 0.0},
 'qd2ad2fea': {'dd2b02da8': 3.880597014925373,
  'dd2af3272': 3.880597014925373,
  'dd2af2336': 3.880597014925373,
  'dd2ade412': 3.298507462686567,
  'dd2ac04a8': 0.0,
  'dd2ad7824': 0.0,
  'dd2ade854': 0.0,
  'dd2af9b04': 0.0,
  'dd2aeab5e': 0.0,
  'dd2ad12e4': 0.0},
 'qd2abc9d4': {'dd2af2336': 1.0,
  'dd2acf5c0': 1.0,
  'dd2ad12e4': 1.0,
  'dd2af3272': 1.0,
  'dd2ade412': 1.0,
  'dd2b02da8': 1.0,
  'dd2aeab5e': 1.0,
  'dd2af9b04': 1.0,
  'dd2ade854': 1.0,
  'dd2ad7824': 1.0},
 'qd2ad6b68': {'dd2af2336': 1.0,
  'dd2acf5c0': 1.0,
  'dd2ad12e4': 1.0,
  'dd2af3272': 1.0,
  'dd2ade412': 1.0,
  'dd2b02da8': 1.0,

In [36]:
hippo_rag.ner_extractor(financebench_task.queries['qd2abbd7c'])

[]

In [35]:
financebench_task.queries['qd2abbd7c']

'Is 3M a capital-intensive business based on FY2022 data?'

In [24]:
g.get_eid('nommi', 'khai', error = False)

-1

In [30]:
g.vs['name']

['khai', 'nommi', 'thu']

In [16]:
from langchain_core.output_parsers import ListOutputParser
import re
class CustomizedListParser(ListOutputParser):
    def parse(self, text) -> List[List[List[str]]]:
        pattern = r"\[\s*(?:\[\s*(?:\[[^\]]*?\]\s*,?\s*\n*)*\s*\]\s*,?\s*)*\s*\]"
        result = re.findall(pattern, text)
        if result:
            extracted_text = re.findall(pattern, text)[0]
            return eval(extracted_text)
        return []

In [17]:
test_str = """

[
 [["Radio City", "located in", "India"],
 ["Radio City", "is", "private FM radio station"],
 ["Radio City", "started on", "3 July 2001"],
 ["Radio City", "plays songs in", "Hindi"],
 ["Radio City", "plays songs in", "English"],
 ["Radio City", "forayed into", "New Media"],
 ["Radio City", "launched", "PlanetRadiocity.com"],
 ["PlanetRadiocity.com", "launched in", "May 2008"],
 ["PlanetRadiocity.com", "is", "music portal"],
 ["PlanetRadiocity.com", "offers", "news"],
 ["PlanetRadiocity.com", "offers", "videos"],
 ["PlanetRadiocity.com", "offers", "songs"]]
 ]
 """

CustomizedListParser().parse(test_str * 100000)

[[['Radio City', 'located in', 'India'],
  ['Radio City', 'is', 'private FM radio station'],
  ['Radio City', 'started on', '3 July 2001'],
  ['Radio City', 'plays songs in', 'Hindi'],
  ['Radio City', 'plays songs in', 'English'],
  ['Radio City', 'forayed into', 'New Media'],
  ['Radio City', 'launched', 'PlanetRadiocity.com'],
  ['PlanetRadiocity.com', 'launched in', 'May 2008'],
  ['PlanetRadiocity.com', 'is', 'music portal'],
  ['PlanetRadiocity.com', 'offers', 'news'],
  ['PlanetRadiocity.com', 'offers', 'videos'],
  ['PlanetRadiocity.com', 'offers', 'songs']]]

In [15]:
for dataset_name in dataset_names:
    task_variable = f"{dataset_name.lower()}_task"
    script_string = f"""
    # {dataset_name} Task
    {task_variable}_final_result = extract_result({task_variable}_result, k = 10)
    {task_variable}.save_retrieved_results({task_variable}_final_result, method_name = 'dense_retrieval_split_only')
    """
    print(script_string)

    # MultiHeirtt Task
    multiheirtt_task_final_result = extract_result(multiheirtt_task_result, k = 10)
    multiheirtt_task.save_retrieved_results(multiheirtt_task_final_result, method_name = 'dense_retrieval_split_only')


    # FinQA Task
    finqa_task_final_result = extract_result(finqa_task_result, k = 10)
    finqa_task.save_retrieved_results(finqa_task_final_result, method_name = 'dense_retrieval_split_only')


    # FinanceBench Task
    financebench_task_final_result = extract_result(financebench_task_result, k = 10)
    financebench_task.save_retrieved_results(financebench_task_final_result, method_name = 'dense_retrieval_split_only')


    # ConvFinQA Task
    convfinqa_task_final_result = extract_result(convfinqa_task_result, k = 10)
    convfinqa_task.save_retrieved_results(convfinqa_task_final_result, method_name = 'dense_retrieval_split_only')


    # FinQABench Task
    finqabench_task_final_result = extract_result(finqabench_task_result, k = 10)
    finqabench_task.save_retrieved_results(finqabench_task_final_result, method_name = 'dense_retrieval_split_only')


    # TATQA Task
    tatqa_task_final_result = extract_result(tatqa_task_result, k = 10)
    tatqa_task.save_retrieved_results(tatqa_task_final_result, method_name = 'dense_retrieval_split_only')


    # FinDER Task
    finder_task_final_result = extract_result(finder_task_result, k = 10)
    finder_task.save_retrieved_results(finder_task_final_result, method_name = 'dense_retrieval_split_only')

In [21]:
def extract_result(task_result : Dict[str, Dict[str, float]], k = 10):
    final_result = {}
    for query_id, doc_dict in task_result.items():
        final_result[query_id] = {}
        for i, (corpus_id, score) in enumerate(doc_dict.items()):
            if (i == k): break
            final_result[query_id][corpus_id] = score
    return final_result

In [22]:

# # FinQA Task
# finqa_task_final_result = extract_result(finqa_task_result, k = 10)
# finqa_task.save_retrieved_results(finqa_task_final_result, method_name = 'dense_retrieval_split_only')


# # FinanceBench Task
# financebench_task_final_result = extract_result(financebench_task_result, k = 10)
# financebench_task.save_retrieved_results(financebench_task_final_result, method_name = 'dense_retrieval_split_only')


# # ConvFinQA Task
# convfinqa_task_final_result = extract_result(convfinqa_task_result, k = 10)
# convfinqa_task.save_retrieved_results(convfinqa_task_final_result, method_name = 'dense_retrieval_split_only')


# # FinQABench Task
# finqabench_task_final_result = extract_result(finqabench_task_result, k = 10)
# finqabench_task.save_retrieved_results(finqabench_task_final_result, method_name = 'dense_retrieval_split_only')


# # TATQA Task
# tatqa_task_final_result = extract_result(tatqa_task_result, k = 10)
# tatqa_task.save_retrieved_results(tatqa_task_final_result, method_name = 'dense_retrieval_split_only')


# FinDER Task
finder_task_final_result = extract_result(finder_task_result, k = 10)
finder_task.save_retrieved_results(finder_task_final_result, method_name = 'dense_retrieval_split_only')

Saved result successfully to ./financerag_result/dense_retrieval_split_only/finder_result.csv!

In [13]:





# TATQA Task
tatqa_task_final_result = extract_result(tatqa_task_result, k = 10)
tatqa_task.save_retrieved_results(tatqa_task_final_result, method_name = 'dense_retrieval_only')


# FinDER Task
finder_task_final_result = extract_result(finder_task_result, k = 10)
finder_task.save_retrieved_results(finder_task_final_result, method_name = 'dense_retrieval_only')

Saved result successfully to ./financerag_result/dense_retrieval_only/tatqa_result.csv!
Saved result successfully to ./financerag_result/dense_retrieval_only/finder_result.csv!

In [26]:
method_name = 'dense_retrieval_split_document_and_reranking'
final_result = get_final_result(dataset_names, method_name = method_name)

In [24]:
final_result

       query_id      corpus_id
0     q82d4c6ec      d8bcdd900
1     q82d4c6ec      d8177a896
2     q82d4c6ec      d8a3219a8
3     q82d4c6ec      d8e8a6550
4     q82d4c6ec      d87914156
...         ...            ...
2155     q00218  BRK.A20232361
2156     q00218  BRK.A20232245
2157     q00218  BRK.A20232333
2158     q00218  BRK.A20230921
2159     q00218  BRK.A20230602

[46710 rows x 2 columns]

In [27]:
final_result

       query_id      corpus_id
0     q82d4c6ec      d81a04fe4
1     q82d4c6ec      d8d83b68e
2     q82d4c6ec      d8d3fbbaa
3     q82d4c6ec      d8d569dde
4     q82d4c6ec      d88be204e
...         ...            ...
2155     q00218  BRK.A20232226
2156     q00218  BRK.A20231068
2157     q00218  BRK.A20231726
2158     q00218  BRK.A20231067
2159     q00218  BRK.A20232649

[46710 rows x 2 columns]

In [28]:
final_result.to_csv(f'submission_{method_name}.csv', index = False)

In [11]:
import torch.nn as nn

In [45]:

# FinQA Task
print(f"FinQA task")
finqa_task = FinQATask()
finqa_task.load()
vector_store = get_vector_store()
finqa_task_retriever = DenseRetrieval(vector_store = vector_store, dataset_name = finqa_task.metadata.dataset_name)
finqa_task_retriever.load_corpus_without_splitting(corpus = finqa_task.corpus, saved_index = False)
finqa_task_result = finqa_task.retrieve(retriever = finqa_task_retriever, top_k = 50)
finqa_task_reranker = CrossEncoderReranker(queries = finqa_task.queries, corpus = finqa_task.corpus, reranker = model)
finqa_task_final_result = finqa_task_reranker.rerank(finqa_task_result, top_k = 10)
finqa_task.save_retrieved_results(finqa_task_final_result, method_name = 'dense_retrieval_and_reranking')

FinQA task

Loading: 100%|██████████| 2789/2789 [00:00<00:00, 223242.63it/s]
Add to vectorDB: 100%|██████████| 2/2 [07:31<00:00, 226.00s/it]
Retrieving result: 100%|██████████| 1147/1147 [07:26<00:00,  2.57it/s]
Reranking: 100%|██████████| 1147/1147 [08:19<00:00,  2.29it/s]

Saved result successfully to ./financerag_result/dense_retrieval_and_reranking/finqa_result.csv!

In [46]:
# # MultiHeirtt Task
# multiheirtt_task_final_result = extract_result(multiheirtt_task_result, k = 10)
# multiheirtt_task.save_retrieved_results(multiheirtt_task_final_result, method_name = 'dense_retrieval_only')


# FinQA Task
finqa_task_final_result = extract_result(finqa_task_result, k = 10)
finqa_task.save_retrieved_results(finqa_task_final_result, method_name = 'dense_retrieval_only')

Saved result successfully to ./financerag_result/dense_retrieval_only/finqa_result.csv!

In [21]:
a = {'s': {'s' : 1}}
isinstance(a, Dict)

True